[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg", "stdenv.cc.cc.lib"]

[phases.install]
cmds = [
  "cd backend && python3 -m venv /app/venv",
  "cd backend && /app/venv/bin/pip install --upgrade pip",
  "cd backend && /app/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/backend/start.sh"
