[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg", "stdenv.cc.cc.lib"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install --upgrade pip",
  "/app/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "LD_LIBRARY_PATH=/nix/store/*-gcc-*/lib:$LD_LIBRARY_PATH /app/venv/bin/python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
